### ISSUE TITLE
doc request: setting use_context and include_sources from pyhon code.

### ISSUE THREAD

**Issue by quincy451** [zylon-ai/pgpt-python#2]
this code from the sample works, but don't know how to include the additional functionality of using ingested documents and including sources in the response:
# Sync completion
print("Sync completion")
print(
    client.contextual_completions.prompt_completion(
        prompt="Answer with just the result: 2+2"
    )
    .choices[0]
    .message.content
)

**Comment by quincy451** [comment]
this works here:
result = client.contextual_completions.prompt_completion(
    prompt="What did Montage do?",
    use_context=True,
    context_filter={"docs_ids": ["8cfc93fa-01dd-4644-82d4-e12dfff54dcf"]},
    include_sources=True,
).choices[0]

**Comment by imartinez** [comment]
it is documented here 

https://github.com/zylon-ai/pgpt-python?tab=readme-ov-file#11-contextual-completion
