### ISSUE TITLE
Running two python versions concurrently

### ISSUE THREAD

**Issue by SeifBach** [zylon-ai/pgpt-python#5]
since creating the privateGPT instance in the localhost 8001requires python 3.11 (and not 3.12)
and importing PrivateGPTApi in the python code requires python 3.12
the way im running it in WSL2 is opening 2 ubuntu command lines interfaces each with a corresponding conda enviorment one to run the instance and one to run the code.
is this the intended way? or did i miss something obvious.

(side note) how do i change the system prompt from my code 
and if i change it from the GUI through additional inputs. does that change apply to the code?

**Comment by imartinez** [comment]
We just released v0.1.2 which lowers the python required version to 3.11 to align it with PrivateGPT
